<!doctype html>
<html lang="ru">
<head>
    <title>MENU</title>
</head>
<body>
<h1>Формирование графика нагрузки</h1><hr>
<div>
    <form action="/loadChart/setLoad" method="post">
        <table>
            <tbody>
            <tr>
                <td>
                    Час 1:  <input type="number" step="any" name="power" value="80"/><br>
                    Час 2:  <input type="number" step="any" name="power" value="80"/><br>
                    Час 3:  <input type="number" step="any" name="power" value="50"/><br>
                    Час 4:  <input type="number" step="any" name="power" value="60"/><br>
                    Час 5:  <input type="number" step="any" name="power" value="50"/><br>
                    Час 6:  <input type="number" step="any" name="power" value="90"/><br>
                    Час 7:  <input type="number" step="any" name="power" value="90"/><br>
                    Час 8:  <input type="number" step="any" name="power" value="100"/><br>
                    Час 9:  <input type="number" step="any" name="power" value="100"/><br>
                    Час 10: <input type="number" step="any" name="power" value="100"/><br>
                    Час 11: <input type="number" step="any" name="power" value="100"/><br>
                    Час 12: <input type="number" step="any" name="power" value="100"/><br>
                </td>
                <td>
                    Час 13: <input type="number" step="any" name="power" value="100"/><br>
                    Час 14: <input type="number" step="any" name="power" value="100"/><br>
                    Час 15: <input type="number" step="any" name="power" value="90"/><br>
                    Час 16: <input type="number" step="any" name="power" value="80"/><br>
                    Час 17: <input type="number" step="any" name="power" value="60"/><br>
                    Час 18: <input type="number" step="any" name="power" value="65"/><br>
                    Час 19: <input type="number" step="any" name="power" value="80"/><br>
                    Час 20: <input type="number" step="any" name="power" value="90"/><br>
                    Час 21: <input type="number" step="any" name="power" value="100"/><br>
                    Час 22: <input type="number" step="any" name="power" value="100"/><br>
                    Час 23: <input type="number" step="any" name="power" value="70"/><br>
                    Час 24: <input type="number" step="any" name="power" value="70"/><br>
                </td>
            </tr>
            </tbody>
        </table>
        <input type="submit" value="Применить"/>
    </form>
</div>
</body>
</html>